### PR TITLE
Use default http client

### PR DESCRIPTION
**Pull request by hazim1093**

### CODE REVIEW

**Comment by stakater-user** [comment]
@hazim1093 Image is available for testing. `docker pull stakater/gitwebhookproxy:PR-10-2`

**Comment by stakater-user** [comment]
@hazim1093 Image is available for testing. `docker pull stakater/gitwebhookproxy:PR-10-3`

**Comment by stakater-user** [comment]
@hazim1093 Yikes! You better fix it before anyone else finds out! [Build 4](https://jenkins.tools.stackator.com/job/Stakater/job/GitWebhookProxy/job/PR-10/4/) has Failed!

**Comment by stakater-user** [comment]
@hazim1093 Image is available for testing. `docker pull stakater/gitwebhookproxy:PR-10-6`

**Comment by stakater-user** [comment]
@hazim1093 Image is available for testing. `docker pull stakater/gitwebhookproxy:PR-10-7`

**Comment by stakater-user** [comment]
@hazim1093 Image is available for testing. `docker pull stakater/gitwebhookproxy:PR-10-8`

**Comment by hazim1093** [comment]
Please don't delete or merge this PR as the issue seems to be with the endpoint and not the client. Still WIP

**Comment by hazim1093** [comment]
Not valid anymore

**Pull request closed without merging**
