### PR TITLE
drop duplicate .version file

### PR DESCRIPTION
**Pull request by davidkarlsen**
You have two .version files with different casing - this makes it hard to use git on some filesystems - and one contains wrong version.

---
This change is [Reviewable](https://reviewable.io/reviews/stakater/gitwebhookproxy/89)

### CODE REVIEW

**Comment by stakater-user** [comment]
@davidkarlsen Image is available for testing. ``docker pull stakater/gitwebhookproxy:SNAPSHOT-PR-89-2``

**Comment by stakater-user** [comment]
@davidkarlsen Image is available for testing. ``docker pull stakater/gitwebhookproxy:SNAPSHOT-PR-89-1``

**Comment by davidkarlsen** [comment]
@hazim1093 PTAL - so that we can get in other fixes after this.

**Review by hamza3202 — APPROVED** [review]

**Comment by hamza3202** [comment]
Thanks @davidkarlsen

**Pull request merged**
