### PR TITLE
Update Github PR Payload

### PR DESCRIPTION
**Pull request by iktl**
Payload not longer reflected what Github sends for `requested_teams` and `labels` which was causing unmarshalling the JSON to fail. Running this image locally to resolve our issues and should knock out #71 and #72.

### CODE REVIEW

**Comment by stakater-user** [comment]
@iktl Image is available for testing. ``docker pull stakater/gitwebhookproxy:SNAPSHOT-PR-73-1``

**Comment by kahootali** [comment]
@iktl Can you please deploy with the above image, `stakater/gitwebhookproxy:SNAPSHOT-PR-73-1` and let us know if it works for you? So I can merge this PR

**Comment by iktl** [comment]
@kahootali ran that image and everything looks good 👍

**Comment by stakater-user** [comment]
@iktl Image is available for testing. ``docker pull stakater/gitwebhookproxy:SNAPSHOT-PR-73-2``

**Pull request merged**
