### PR TITLE
allow ignoredUser and allowedUser values to be empty

### PR DESCRIPTION
**Pull request by stefan-mees**

### CODE REVIEW

**Comment by stakater-user** [comment]
@stefan-mees Image is available for testing. ``docker pull stakater/gitwebhookproxy:SNAPSHOT-PR-85-1``

**Comment by rasheedamir** [comment]
@stefan-mees can you plz update your branch?

**Comment by stakater-user** [comment]
@stefan-mees Image is available for testing. ``docker pull stakater/gitwebhookproxy:SNAPSHOT-PR-85-2``

**Comment by stakater-user** [comment]
@stefan-mees Yikes! You better fix it before anyone else finds out! [Build 3](https://jenkins-delivery.stakater.com/job/Stakater/job/GitWebhookProxy/job/PR-85/3/) has Failed!

**Comment by davidkarlsen** [comment]
@hamza3202 this is now obsolete

**Comment by hamza3202** [comment]
@stefan-mees thanks for the PR, but this functionality is already made available in [90](https://github.com/stakater/GitWebhookProxy/pull/90)

**Pull request closed without merging**
