### PR TITLE
Use correct Ingress apiVersion

### PR DESCRIPTION
**Pull request by joshbranham**
This is generating an out of date Ingress apiVersion (deprecated since `1.14`)

Update the `Ingress` to be compliant with supported Kubernetes versions.

### CODE REVIEW

**Review by davidkarlsen — APPROVED** [review]

**Comment by davidkarlsen** [comment]
@joshbranham can you add the rest?

**Comment by joshbranham** [comment]
Sure I can work on that, although should we just remove the conditionals and have the `Ingress` be only compliant for `> 1.14` since that K8s version is EOL anyways..?

If so I can just do that instead.

**Review by davidkarlsen — CHANGES_REQUESTED** [review]
The actual contents of the resource needs some changes to adhere to the updated spec version.

**Comment by davidkarlsen** [comment]
> Sure I can work on that, although should we just remove the conditionals and have the `Ingress` be only compliant for `> 1.14` since that K8s version is EOL anyways..?
> 
> If so I can just do that instead.

I think that would be reasonable, yes.

**Comment by joshbranham** [comment]
> The actual contents of the resource needs some changes to adhere to the updated spec version.

Yup that is the piece I had not added yet, but my comment above is asking if we should just make those on `master` here versus handling an EOL K8s API version + spec.

**Comment by joshbranham** [comment]
I believe it is updated now, there are some lingering conditionals and things that could be cleaned up (like `customName` could just be a default `values.yaml` someone changes? I bumped the version as well.

**Review by davidkarlsen — APPROVED** [review]

**Pull request merged**
