### PR TITLE
Fix type conversion error, cannot unmarshal string into Go struct field .created_at of type int64

### PR DESCRIPTION
**Pull request by ahmedwaleedmalik**
Error: Github payload unmarshaling failed for Push event: json: cannot unmarshal string into Go struct field .created_at of type int64

### CODE REVIEW

**Comment by stakater-user** [comment]
@ahmedwaleedmalik Image is available for testing. ``docker pull stakater/gitwebhookproxy:SNAPSHOT-PR-79-4``

**Comment by stakater-user** [comment]
@ahmedwaleedmalik Image is available for testing. ``docker pull stakater/gitwebhookproxy:SNAPSHOT-PR-79-6``

**Comment by stakater-user** [comment]
@ahmedwaleedmalik Image is available for testing. ``docker pull stakater/gitwebhookproxy:SNAPSHOT-PR-79-7``

**Comment by stakater-user** [comment]
@ahmedwaleedmalik Image is available for testing. ``docker pull stakater/gitwebhookproxy:SNAPSHOT-PR-79-8``

**Comment by stakater-user** [comment]
@ahmedwaleedmalik Image is available for testing. ``docker pull stakater/gitwebhookproxy:SNAPSHOT-PR-79-9``

**Comment by stakater-user** [comment]
@ahmedwaleedmalik Image is available for testing. ``docker pull stakater/gitwebhookproxy:SNAPSHOT-PR-79-10``

**Comment by ahmedwaleedmalik** [comment]
Closed because the change is not required anymore

**Pull request closed without merging**
