### PR TITLE
Fixes #80

### LINKED ISSUE #80: allowedusers logic should allow empty list
It seems that the proxy requires to whitelist all users: https://github.com/stakater/GitWebhookProxy/blob/035d2b417545d2781746c3147fabd9ac93a27b1d/pkg/proxy/proxy.go#L73

https://github.com/stakater/GitWebhookProxy/blob/035d2b417545d2781746c3147fabd9ac93a27b1d/pkg/proxy/proxy.go#L145

Would it make more sense to the allow-check if arraysize > 0, else accept it? It seems a bit cumbersome to have to list each and every user.

### PR DESCRIPTION
**Pull request by davidkarlsen**
Signed-off-by: David Karlsen <david@davidkarlsen.com>

---
This change is [Reviewable](https://reviewable.io/reviews/stakater/gitwebhookproxy/81)

### CODE REVIEW

**Comment by stakater-user** [comment]
@davidkarlsen Yikes! You better fix it before anyone else finds out! [Build 7](https://jenkins-delivery.stakater.com/job/Stakater/job/GitWebhookProxy/job/PR-81/7/) has Failed!

**Comment by stakater-user** [comment]
@davidkarlsen Image is available for testing. ``docker pull stakater/gitwebhookproxy:SNAPSHOT-PR-81-8``

**Comment by kahootali** [comment]
@davidkarlsen the image is available, can you please check and verify it and then I can merge the PR

**Comment by davidkarlsen** [comment]
It works fine! Also the charts is missing templating in the configmap for `secret` (the shared secret to verify hashes).

**Pull request merged**
